package entidades;
// Generated 24/06/2019 12:04:34 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido;
     private Date fechanac;
     private int telefono;
     private String direcion;
     private String gmail;

    public Cliente() {
    }

    public Cliente(int idCliente, String nombre, String apellido, Date fechanac, int telefono, String direcion, String gmail) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechanac = fechanac;
       this.telefono = telefono;
       this.direcion = direcion;
       this.gmail = gmail;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getDirecion() {
        return this.direcion;
    }
    
    public void setDirecion(String direcion) {
        this.direcion = direcion;
    }
    public String getGmail() {
        return this.gmail;
    }
    
    public void setGmail(String gmail) {
        this.gmail = gmail;
    }




}


