package entidades;
// Generated 14/07/2019 05:08:27 PM by Hibernate Tools 4.3.1



/**
 * MascotaporclienteId generated by hbm2java
 */
public class MascotaporclienteId  implements java.io.Serializable {


     private int codigoCliente;
     private int codigoMascota;

    public MascotaporclienteId() {
    }

    public MascotaporclienteId(int codigoCliente, int codigoMascota) {
       this.codigoCliente = codigoCliente;
       this.codigoMascota = codigoMascota;
    }
   
    public int getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(int codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public int getCodigoMascota() {
        return this.codigoMascota;
    }
    
    public void setCodigoMascota(int codigoMascota) {
        this.codigoMascota = codigoMascota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MascotaporclienteId) ) return false;
		 MascotaporclienteId castOther = ( MascotaporclienteId ) other; 
         
		 return (this.getCodigoCliente()==castOther.getCodigoCliente())
 && (this.getCodigoMascota()==castOther.getCodigoMascota());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoCliente();
         result = 37 * result + this.getCodigoMascota();
         return result;
   }   


}


