package entidades;
// Generated 14/07/2019 05:08:27 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Perfil perfil;
     private Personal personal;
     private String usuario;
     private String clave;
     private char estado;

    public Usuario() {
    }

    public Usuario(int idUsuario, Perfil perfil, Personal personal, String usuario, String clave, char estado) {
       this.idUsuario = idUsuario;
       this.perfil = perfil;
       this.personal = personal;
       this.usuario = usuario;
       this.clave = clave;
       this.estado = estado;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


